### ISSUE TITLE
Max lines on one page not working in some instances

### ISSUE THREAD

**Issue by arne182** [tim4724/u-song-Stage-Monitor-for-Songbeamer#8]
Last slide not being split into 2 lines but shows as 3 even though settings have max line as 2.
![image](https://user-images.githubusercontent.com/844102/107050821-fae0f180-67cb-11eb-8778-4d164ad977f5.png)
Here is the song as input into songbeamer:
Go tell it on the mountain,
Over the hills
and everywhere;
Go tell it on the mountain,
That Jesus Christ is born.
---
While shepherds kept
their watching,
O'er silent flocks by night;
Behold throughout the heavens,
There shone a holy light.
---
And lo, when they had seen it,
They all bowed down
and prayed;
They traveled on together
To where the Babe was laid.
---
The shepherds feared
and trembled,
When lo above the earth;
Rang out the angel chorus,
That hailed our Savior's birth.
---
Down in a lowly manger,
The humble Christ was born;
And brought us
God's salvation,
That blessed Christmas morn.

**Comment by arne182** [comment]
It looks like it is only the last page that is not split correctly
![image](https://user-images.githubusercontent.com/844102/107053438-18638a80-67cf-11eb-9873-68bd18a742cc.png)
But only if there is one more line than the max line settings.
![image](https://user-images.githubusercontent.com/844102/107053507-2f09e180-67cf-11eb-8ec8-eda26246d3d9.png)

**Comment by tim4724** [comment]
Hello Arne :)

Thank you for reporting. Apparently the behaviour of Songbeamer changed in a recent version. 

The last time I checked, Songbeamer was also displaying one more line in the last page, in order to avoid a slide with only one line.
The SongBeamer Changelog for version 5.07 mentions the maximum lines setting ("Maximale Zeilenanzahl pro Seite hat nicht immer korrekt funktioniert" https://www.songbeamer.de/download.htm) 

I will update the application and notify you when the fix is ready.

**Comment by arne182** [comment]
Thanks for still working on this. I was wondering if is was possible to have the slide number printed in the preview?

**Comment by tim4724** [comment]
You are welcome. It is great to know that someone is using the software.

**Comment by arne182** [comment]
![image](https://user-images.githubusercontent.com/844102/107054251-2665db00-67d0-11eb-8f45-c06b8021337e.png)
This is my current setup with the Companion app pressing the button for the correct slide

**Comment by arne182** [comment]
Just as an aside: Malwarebytes was complaining on starting the app
![image](https://user-images.githubusercontent.com/844102/107054721-c7ed2c80-67d0-11eb-813f-23356dfc3648.png)
I assume that there is nothing that can be done but FYI

**Comment by tim4724** [comment]
I think I can add the page number in the preview window.

**Comment by tim4724** [comment]
I did not know about this, since I do not use any third party antivirus software.

According to that site https://blog.malwarebytes.com/detections/malware-exploit-agent-generic/
Malwarebytes assumes this is an exploit that has not yet been classified. 
I assume, Malwarebytes thinks it is suspicious behaviour, because a java application is calling an exe file. Which is not very usual.

But yes, sadly there is nothing that I can do...

**Comment by tim4724** [comment]
There is another thing, that is not working correctly.
Since you are able to manually set the maximum number of lines. Apparently my software failed to read the Songbeamer Settings file. 

There is a file, that should be located at "%appdata%" -> "Songbeamer/SBConfig.sfs4"

Could you please send me that file?

**Comment by arne182** [comment]
[SBConfig.zip](https://github.com/tim4724/u-song-Stage-Monitor-for-Songbeamer/files/5933898/SBConfig.zip)

**Comment by tim4724** [comment]
@arne182 
I published a new release (2.2.3) that should fix the max lines problem.

Also you can now view the page numbers if you open the following address in your browser:
http://192.168.188.120/song?admin=true&showPageNumbers=true

I could not understand, why you have to configure the max lines manually in the settings. But this is not a serious bug, so I will not look into it further for now.

**Comment by tim4724** [comment]
I noticed that there is still a problem with some multilanguage songs in combination with max lines set. It seems Songbeamer changed how a song is displayed in a recent update. At the moment, I do not understand how Songbeamer is reading the song file.

**Comment by tim4724** [comment]
Ok I found a bug in songbeamer. :)

I set maximum lines to 3. This is the result. 

![songbeamer_bug](https://user-images.githubusercontent.com/15907780/107073245-67b5b500-67e7-11eb-95e5-733420bfe7b7.png)

There are only 2 lines on the first slide. And "Hallo 3" is displayed with the wrong color and wrong font style.

**Comment by arne182** [comment]
Working
